export const caseStudies = {
  'imitation-book': {
    slug: 'imitation-book',
    index: 0,
    breadcrumb: 'WEBIK / WORK / 01 — IMITATION BOOK',
    title: 'Imitation Book',
    subtitle: 'A speech-therapy publishing brand that helps little ones learn to talk.',
    category: 'E-COMMERCE · PUBLISHING',
    client: 'Twin Cities Speech Therapy Publishing, USA',
    year: '2025',
    scope: 'Shopify · Web Design · Web Development · Branding',
    liveUrl: 'https://imitationbook.com',
    liveDomain: 'WWW.IMITATIONBOOK.COM',
    mockupUrl: 'https://webikdigital.com/wp-content/uploads/2025/11/Macbook_Air_M2_Mockup_2-2-1-1024x768.png',
    thumbnailUrl: 'https://media.base44.com/images/public/69ecce3288377cd246349884/80984f361_generated_image.png',
    brief: [
      'Twin Cities Speech Therapy Publishing was founded by a mom and licensed speech-language pathologist with a passion for making communication easier — and more fun — for little ones.',
      'They needed a Shopify storefront that felt as warm and approachable as the brand itself, while supporting a growing catalog of educational products for parents.',
    ],
    approach: [
      { num: '01', title: 'Warmth as a feature', desc: 'Speech therapy can feel clinical. We chose colors and type that feel like a children\'s book — playful, but trustworthy.' },
      { num: '02', title: 'Built for parent-shoppers', desc: 'Every product page answers the questions a tired parent actually asks before buying.' },
      { num: '03', title: 'Conversion-focused checkout', desc: 'A streamlined Shopify build that gets parents from "this could help" to "thank you for your order" in under 90 seconds.' },
      { num: '04', title: 'Story-led homepage', desc: 'We led with the founder\'s mission, not a banner sale. Trust before transaction.' },
    ],
    pageTour: [
      { name: 'Home', label: 'PAGE 01', desc: 'On a mission to make communication easier — and more fun — for little ones.' },
      { name: 'Books', label: 'PAGE 02', desc: 'Get started with a best-seller and make your child\'s learning more exciting.' },
      { name: 'Products', label: 'PAGE 03', desc: 'A curated collection essential for early-childhood communication development.' },
    ],
    typography: {
      primary: 'Freude',
      body: 'Poppins',
      specimen: 'Aa',
      scale: [
        { label: 'H1', size: '76px' },
        { label: 'H2', size: '42px' },
        { label: 'H3', size: '32px' },
        { label: 'H4', size: '28px' },
        { label: 'Body', size: '18px' },
      ],
    },
    palette: [
      { name: 'Pumpkin Spice', hex: '#F8941D', rgb: 'R248 G148 B29' },
      { name: 'Deep Teal', hex: '#4FC2C9', rgb: 'R79 G194 B201' },
      { name: 'Bitter Lime', hex: '#B2D336', rgb: 'R178 G211 B54' },
      { name: 'Glacier Mist', hex: '#E0F3FA', rgb: 'R224 G243 B250' },
      { name: 'Sunstone Gold', hex: '#FFCC5C', rgb: 'R255 G204 B92' },
      { name: 'Eerie Black', hex: '#1E1E1E', rgb: 'R30 G30 B30' },
      { name: 'Pure White', hex: '#FFFFFF', rgb: 'R255 G255 B255' },
    ],
    techStack: ['Shopify', 'Custom Theme Dev', 'GitHub Versioning', 'Mobile-First', 'SEO + AEO Schema'],
    quote: null,
  },

  'bitlyft': {
    slug: 'bitlyft',
    index: 1,
    breadcrumb: 'WEBIK / WORK / 02 — BITLYFT',
    title: 'BitLyft Cybersecurity',
    subtitle: 'Enterprise-grade cybersecurity, made personal for mid-sized businesses.',
    category: 'TECH · CYBERSECURITY (MSSP)',
    client: 'BitLyft Cybersecurity, USA',
    year: '2025',
    scope: 'Web Design · Web Development · Brand System',
    liveUrl: 'https://bitlyft.com',
    liveDomain: 'WWW.BITLYFT.COM',
    mockupUrl: 'https://webikdigital.com/wp-content/uploads/2025/08/BitLyft-mockup-1024x708.png',
    thumbnailUrl: 'https://media.base44.com/images/public/69ecce3288377cd246349884/79b3b38ef_generated_image.png',
    brief: [
      'BitLyft is a leading managed security service provider, dedicated to delivering mid-sized organizations with high-touch, personalized cybersecurity solutions.',
      'They needed a website that signaled enterprise credibility without alienating the smaller IT teams who actually buy from them.',
    ],
    approach: [
      { num: '01', title: 'Authority through restraint', desc: 'Cybersecurity buyers don\'t trust loud websites. We led with whitespace, calm typography, and confidence.' },
      { num: '02', title: 'Made for the IT decision-maker', desc: 'Information architecture built around the questions an IT director asks at 11pm before a renewal.' },
      { num: '03', title: 'Service-first navigation', desc: 'We pushed their managed services and platform up — testimonials and team came after the proof.' },
      { num: '04', title: 'Performance as proof', desc: 'A cybersecurity company can\'t have a slow site. We obsessed over Core Web Vitals.' },
    ],
    pageTour: [
      { name: 'Home', label: 'PAGE 01', desc: 'A range of managed security services and a proprietary platform built for mid-sized organizations.' },
      { name: 'About', label: 'PAGE 02', desc: 'A leading MSSP delivering high-touch, personalized cybersecurity solutions.' },
      { name: 'Contact', label: 'PAGE 03', desc: 'For mid-sized businesses needing to improve cybersecurity without in-house expertise.' },
    ],
    typography: {
      primary: 'Figtree ExtraBold',
      body: 'Poppins',
      specimen: 'Aa',
      scale: [
        { label: 'H1', size: '76px' },
        { label: 'H2', size: '42px' },
        { label: 'H3', size: '32px' },
        { label: 'H4', size: '28px' },
        { label: 'Body', size: '18px' },
      ],
    },
    palette: [
      { name: 'Royal Blue', hex: '#2261DB', rgb: 'R34 G97 B219' },
      { name: 'Midnight Blue', hex: '#03173F', rgb: 'R3 G23 B63' },
      { name: 'Steel Blue', hex: '#81AFDD', rgb: 'R129 G175 B221' },
      { name: 'Battleship Gray', hex: '#A7A5A5', rgb: 'R167 G165 B165' },
      { name: 'Black', hex: '#000000', rgb: 'R0 G0 B0' },
      { name: 'White', hex: '#FFFFFF', rgb: 'R255 G255 B255' },
    ],
    techStack: ['WordPress', 'Bricks Builder', 'Custom Development', 'GitHub Deployment', 'SEO + AEO Schema', 'Performance-Tuned'],
    quote: null,
  },

  'biosis-designs': {
    slug: 'biosis-designs',
    index: 2,
    breadcrumb: 'WEBIK / WORK / 03 — BIOSIS DESIGNS',
    title: 'Biosis Designs',
    subtitle: 'Architecture that resonates. Design that breathes.',
    category: 'ARCHITECTURE · DESIGN STUDIO',
    client: 'Biosis Designs, Architectural Design Firm',
    year: '2025',
    scope: 'Web Design · Web Development · Brand Implementation',
    liveUrl: 'https://biosisdesigns.com',
    liveDomain: 'WWW.BIOSISDESIGNS.COM',
    mockupUrl: 'https://webikdigital.com/wp-content/uploads/2025/08/Biosys-mockup-1024x708.png',
    thumbnailUrl: 'https://media.base44.com/images/public/69ecce3288377cd246349884/72a560d3f_generated_image.png',
    brief: [
      'Biosis Designs redefines architectural design by combining visionary thinking and technical precision to deliver spaces that resonate.',
      'They needed a portfolio website that matched the calm intentionality of their built work — clean, considered, and quietly confident.',
    ],
    approach: [
      { num: '01', title: 'Whitespace as architecture', desc: 'We treated negative space the way they treat physical space — as a feature, not a gap.' },
      { num: '02', title: 'Project-first storytelling', desc: 'The work speaks first. Brand voice supports, but doesn\'t compete.' },
      { num: '03', title: 'Calm interactions', desc: 'No splashy hover effects. Subtle, slow, intentional — like walking through one of their spaces.' },
      { num: '04', title: 'Client-journey clarity', desc: 'From discovery to project delivery, the site walks visitors through their thoughtful process.' },
    ],
    pageTour: [
      { name: 'About', label: 'PAGE 01', desc: 'Creates thoughtful, functional spaces that elevate everyday living through purposeful architecture.' },
      { name: 'Projects', label: 'PAGE 02', desc: 'Carefully crafted spaces reflecting the client\'s vision through balance, detail, and intentional design.' },
      { name: 'Contact', label: 'PAGE 03', desc: 'Collaborate on a project that brings your vision to life with clarity, creativity, and care.' },
    ],
    typography: {
      primary: 'Aeonik',
      body: 'Instrument Sans',
      specimen: 'Aa',
      scale: [
        { label: 'H1', size: '76px' },
        { label: 'H2', size: '42px' },
        { label: 'H3', size: '32px' },
        { label: 'H4', size: '28px' },
        { label: 'Body', size: '18px' },
      ],
    },
    palette: [
      { name: 'Green Sheen', hex: '#52A591', rgb: 'R82 G165 B145' },
      { name: 'Charcoal Green', hex: '#354B45', rgb: 'R53 G75 B69' },
      { name: 'Cambridge Blue', hex: '#98B0A9', rgb: 'R152 G176 B169' },
      { name: 'Light Mist Gray', hex: '#EBEEF0', rgb: 'R235 G238 B240' },
      { name: 'White', hex: '#FFFFFF', rgb: 'R255 G255 B255' },
      { name: 'Eerie Black', hex: '#1E1E1E', rgb: 'R30 G30 B30' },
      { name: 'Dark Gray', hex: '#A3A3A3', rgb: 'R163 G163 B163' },
    ],
    techStack: ['WordPress', 'Bricks Builder', 'Custom Animations', 'GitHub Deployment', 'SEO + AEO Schema'],
    quote: null,
  },

  'the-genesis-company': {
    slug: 'the-genesis-company',
    index: 3,
    breadcrumb: 'WEBIK / WORK / 04 — THE GENESIS COMPANY',
    title: 'The Genesis Company',
    subtitle: 'Strategic partners coordinating growth across every part of your business.',
    category: 'BUSINESS · STRATEGY CONSULTING',
    client: 'The Genesis Company, USA',
    year: '2025',
    scope: 'Web Design · Web Development · Brand System',
    liveUrl: 'https://thegenesiscompany.com',
    liveDomain: 'WWW.THEGENESISCOMPANY.COM',
    mockupUrl: 'https://webikdigital.com/wp-content/uploads/2025/08/Genesis-mockup-1024x708.png',
    thumbnailUrl: 'https://media.base44.com/images/public/69ecce3288377cd246349884/a37516163_generated_image.png',
    brief: [
      'The Genesis Company is a strategic partner coordinating growth strategy across all aspects of your business — passionate about creating better stories for the brands they serve and the communities they impact.',
      'They needed a site that felt as energetic and color-rich as the work they do.',
    ],
    approach: [
      { num: '01', title: 'Energy through color', desc: 'We leaned into a bold multi-color palette — most consultancies hide. Genesis stands out.' },
      { num: '02', title: 'Story-driven structure', desc: 'Every section opens with the "why" before the "what."' },
      { num: '03', title: 'Built for partnership leads', desc: 'Clear pathways for both new clients and brand partnership inquiries.' },
      { num: '04', title: 'Scalable design system', desc: 'A flexible design system Genesis can grow into across future service lines.' },
    ],
    pageTour: [
      { name: 'Home', label: 'PAGE 01', desc: 'Your strategic partner, coordinating growth strategy across all aspects of your business.' },
      { name: 'About', label: 'PAGE 02', desc: 'Focused on making lives better — for the brands they serve and the wider community.' },
      { name: 'Contact', label: 'PAGE 03', desc: 'For brands looking for a strategic partner to help with growth.' },
    ],
    typography: {
      primary: 'Futura Hv BT',
      body: 'Rubik',
      specimen: 'Aa',
      scale: [
        { label: 'H1', size: '76px' },
        { label: 'H2', size: '42px' },
        { label: 'H3', size: '32px' },
        { label: 'H4', size: '28px' },
        { label: 'Body', size: '18px' },
      ],
    },
    palette: [
      { name: 'Tangerine', hex: '#FF6C02', rgb: 'R255 G108 B2' },
      { name: 'Cyan', hex: '#0ABFFF', rgb: 'R10 G191 B255' },
      { name: 'Slate Blue', hex: '#22445D', rgb: 'R34 G68 B93' },
      { name: 'Canary Yellow', hex: '#FDD231', rgb: 'R253 G210 B49' },
      { name: 'Chartreuse', hex: '#C8F401', rgb: 'R200 G244 B1' },
      { name: 'Kelly Green', hex: '#41D11D', rgb: 'R65 G209 B29' },
      { name: 'White', hex: '#FFFFFF', rgb: 'R255 G255 B255' },
      { name: 'Black', hex: '#000000', rgb: 'R0 G0 B0' },
    ],
    techStack: ['WordPress', 'Bricks Builder', 'Custom Animations', 'GitHub Deployment', 'SEO + AEO Schema'],
    quote: {
      text: 'Working with Pryce on our website was a fantastic experience. He was very responsive, professional, and quick to turn things around without sacrificing quality. Pryce took the time to understand our needs, offered thoughtful options, and made the entire process smooth and stress-free.',
      author: 'Tiana Emery',
      role: 'Director of Client Value, The Genesis Company',
    },
  },
};

export const slugOrder = ['imitation-book', 'bitlyft', 'biosis-designs', 'the-genesis-company'];

export function getNextProject(currentSlug) {
  const idx = slugOrder.indexOf(currentSlug);
  const nextSlug = slugOrder[(idx + 1) % slugOrder.length];
  return caseStudies[nextSlug];
}